Name:           ros-kinetic-astuff-sensor-msgs
Version:        2.0.1
Release:        0%{?dist}
Summary:        ROS astuff_sensor_msgs package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-delphi-esr-msgs
Requires:       ros-kinetic-delphi-srr-msgs
Requires:       ros-kinetic-ibeo-msgs
Requires:       ros-kinetic-kartech-linear-actuator-msgs
Requires:       ros-kinetic-mobileye-560-660-msgs
Requires:       ros-kinetic-neobotix-usboard-msgs
Requires:       ros-kinetic-pacmod-msgs
BuildRequires:  ros-kinetic-catkin

%description
Messages specific to AStuff-provided sensors.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Apr 25 2018 AutonomouStuff Software Development Team <software@autonomoustuff.com> - 2.0.1-0
- Autogenerated by Bloom

