%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-delphi-esr-msgs
Version:        3.3.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS delphi_esr_msgs package

License:        MIT
URL:            http://wiki.ros.org/delphi_esr_msgs
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-rosbag-migration-rule
Requires:       ros-noetic-std-msgs
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-ros-environment
BuildRequires:  ros-noetic-rosbag-migration-rule
BuildRequires:  ros-noetic-std-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-noetic-rosidl-interface-packages(member)

%if 0%{?with_weak_deps}
Supplements:    ros-noetic-rosidl-interface-packages(all)
%endif

%description
Message definitions for the Delphi ESR

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Jun 18 2021 AutonomouStuff Software Team <software@autonomoustuff.com> - 3.3.0-1
- Autogenerated by Bloom

* Fri Mar 12 2021 AutonomouStuff Software Team <software@autonomoustuff.com> - 3.2.0-1
- Autogenerated by Bloom

* Wed Jun 17 2020 AutonomouStuff Software Team <software@autonomoustuff.com> - 3.1.0-1
- Autogenerated by Bloom

